site_name: Yggdrasil Screen Reader
site_url: https://yggdrasil-sr.github.io
site_author: The Yggdrasil contributors
copyright: Copyright © 2021 the Yggdrasil contributors
site_description: |
  A modern, feature-rich screen reader for the Linux desktop, built in Rust.

repo_url: https://github.com/yggdrasil-sr/site

nav:
  - Home: index.md

markdown_extensions:
  - def_list
  - codehilite
  - sane_lists
  - smarty
  - toc:
      permalink: True
