name: Build Site using MkDocs

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    name: Build and Deploy Site
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Main
        uses: actions/checkout@v2

      - name: Checkout Github Pages Repo
        uses: actions/checkout@v2
        with:
          repository: 'yggdrasil-sr/yggdrasil-sr.github.io'
          path: '

      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs-material

      - name: Deploy
        run: |
          git pull
          mkdocs build
          cd site
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add --all
          git commit -m 'Regenerate site'
          git push

